export interface PayerBenefitData {
  payerName: string;
  planType: string;
  planName: string;
  payerPhone: string;
  annualMaximum: number;
  annualMaximumUsed: number;
  deductible: number;
  deductibleMet: boolean;
  deductibleRemaining: number;
  preventiveCoverage: number;
  basicCoverage: number;
  majorCoverage: number;
  orthodonticCoverage: number;
  waitingPeriodBasic: string;
  waitingPeriodMajor: string;
  inNetworkCoverage: number;
  outOfNetworkCoverage: number;
  enrollmentDate: string;
  treatmentRules: Record<string, TreatmentRule>;
}

export interface TreatmentRule {
  covered: boolean;
  coveragePercentage: number;
  frequencyLimit: string;
  preAuthRequired: boolean;
  preAuthThreshold?: number;
  waitingPeriod: string;
  notes: string;
  typicalCost: number;
}

const MOCK_PAYER_DATABASE: Record<string, PayerBenefitData> = {
  "Delta Dental": {
    payerName: "Delta Dental",
    planType: "PPO",
    planName: "Delta Dental PPO Plus Premier",
    payerPhone: "1-800-932-0783",
    annualMaximum: 2000,
    annualMaximumUsed: 320,
    deductible: 50,
    deductibleMet: true,
    deductibleRemaining: 0,
    preventiveCoverage: 100,
    basicCoverage: 80,
    majorCoverage: 50,
    orthodonticCoverage: 50,
    waitingPeriodBasic: "None",
    waitingPeriodMajor: "None",
    inNetworkCoverage: 80,
    outOfNetworkCoverage: 60,
    enrollmentDate: "2022-01-01",
    treatmentRules: {
      "Composite Filling": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per surface per 2 years",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic restorative. Composite resin covered on posterior teeth at amalgam rate.",
        typicalCost: 250,
      },
      "Dental Crown": {
        covered: true,
        coveragePercentage: 50,
        frequencyLimit: "Once per tooth per 5 years",
        preAuthRequired: false,
        preAuthThreshold: 500,
        waitingPeriod: "None",
        notes: "Major restorative. Pre-auth not required under $500 cost.",
        typicalCost: 1300,
      },
      "Root Canal": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per tooth per lifetime",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic endodontic procedure.",
        typicalCost: 900,
      },
      "Dental Implant": {
        covered: true,
        coveragePercentage: 50,
        frequencyLimit: "Once per site per 7 years",
        preAuthRequired: true,
        waitingPeriod: "12 months",
        notes: "Subject to missing tooth clause. Pre-authorization required.",
        typicalCost: 3500,
      },
      "Periodontal Scaling": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per quadrant per 2 years",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic periodontic service.",
        typicalCost: 400,
      },
      "Orthodontics": {
        covered: true,
        coveragePercentage: 50,
        frequencyLimit: "Once per lifetime",
        preAuthRequired: true,
        waitingPeriod: "12 months",
        notes: "Lifetime orthodontic max $1,500. Pre-auth required.",
        typicalCost: 5000,
      },
      "Teeth Whitening": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: false,
        waitingPeriod: "Not applicable",
        notes: "Cosmetic procedures are not covered under this plan.",
        typicalCost: 500,
      },
      "Tooth Extraction": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "As needed",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Simple and surgical extractions covered as oral surgery.",
        typicalCost: 300,
      },
    },
  },

  "Cigna Dental": {
    payerName: "Cigna Dental",
    planType: "PPO",
    planName: "Cigna Dental 1500 PPO",
    payerPhone: "1-800-244-6224",
    annualMaximum: 1500,
    annualMaximumUsed: 1100,
    deductible: 75,
    deductibleMet: false,
    deductibleRemaining: 25,
    preventiveCoverage: 100,
    basicCoverage: 80,
    majorCoverage: 50,
    orthodonticCoverage: 0,
    waitingPeriodBasic: "None",
    waitingPeriodMajor: "12 months from enrollment",
    inNetworkCoverage: 80,
    outOfNetworkCoverage: 50,
    enrollmentDate: "2023-02-01",
    treatmentRules: {
      "Composite Filling": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per surface per 2 years",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic restorative.",
        typicalCost: 250,
      },
      "Dental Crown": {
        covered: true,
        coveragePercentage: 50,
        frequencyLimit: "Once per tooth per 5 years",
        preAuthRequired: true,
        preAuthThreshold: 800,
        waitingPeriod: "12 months from enrollment",
        notes: "Major restorative. Pre-auth required if cost exceeds $800. Waiting period is 14 months from enrollment — CLEARED.",
        typicalCost: 1300,
      },
      "Root Canal": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per tooth per lifetime",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic endodontic procedure.",
        typicalCost: 900,
      },
      "Dental Implant": {
        covered: true,
        coveragePercentage: 50,
        frequencyLimit: "Once per site per 7 years",
        preAuthRequired: true,
        waitingPeriod: "24 months from enrollment",
        notes: "Implants subject to extended waiting period and missing tooth clause.",
        typicalCost: 3500,
      },
      "Periodontal Scaling": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "Once per quadrant per 2 years",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Covered as basic periodontic service.",
        typicalCost: 400,
      },
      "Orthodontics": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: false,
        waitingPeriod: "Not applicable",
        notes: "Orthodontic coverage not included in this plan.",
        typicalCost: 5000,
      },
      "Teeth Whitening": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: false,
        waitingPeriod: "Not applicable",
        notes: "Cosmetic procedures not covered.",
        typicalCost: 500,
      },
      "Tooth Extraction": {
        covered: true,
        coveragePercentage: 80,
        frequencyLimit: "As needed",
        preAuthRequired: false,
        waitingPeriod: "None",
        notes: "Simple and surgical extractions covered.",
        typicalCost: 300,
      },
    },
  },

  "Aetna Dental": {
    payerName: "Aetna Dental",
    planType: "DHMO",
    planName: "Aetna Dental Access DHMO",
    payerPhone: "1-800-872-3862",
    annualMaximum: 1000,
    annualMaximumUsed: 0,
    deductible: 100,
    deductibleMet: false,
    deductibleRemaining: 100,
    preventiveCoverage: 100,
    basicCoverage: 70,
    majorCoverage: 40,
    orthodonticCoverage: 0,
    waitingPeriodBasic: "3 months",
    waitingPeriodMajor: "12 months",
    inNetworkCoverage: 70,
    outOfNetworkCoverage: 40,
    enrollmentDate: "2025-11-01",
    treatmentRules: {
      "Composite Filling": {
        covered: true,
        coveragePercentage: 70,
        frequencyLimit: "Once per surface per 2 years",
        preAuthRequired: false,
        waitingPeriod: "3 months",
        notes: "Basic restorative. Waiting period applies.",
        typicalCost: 250,
      },
      "Dental Crown": {
        covered: true,
        coveragePercentage: 40,
        frequencyLimit: "Once per tooth per 5 years",
        preAuthRequired: true,
        waitingPeriod: "12 months",
        notes: "Major restorative. Pre-auth required.",
        typicalCost: 1300,
      },
      "Root Canal": {
        covered: true,
        coveragePercentage: 70,
        frequencyLimit: "Once per tooth per lifetime",
        preAuthRequired: false,
        waitingPeriod: "3 months",
        notes: "Basic endodontic covered after waiting period.",
        typicalCost: 900,
      },
      "Dental Implant": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: true,
        waitingPeriod: "Not applicable",
        notes: "IMPLANTS NOT COVERED under this DHMO plan. Missing tooth clause applies. Pre-auth required for any surgical procedure. Patient should consult out-of-network options.",
        typicalCost: 3500,
      },
      "Periodontal Scaling": {
        covered: true,
        coveragePercentage: 70,
        frequencyLimit: "Once per quadrant per 2 years",
        preAuthRequired: false,
        waitingPeriod: "3 months",
        notes: "Periodontic services covered after waiting period.",
        typicalCost: 400,
      },
      "Orthodontics": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: false,
        waitingPeriod: "Not applicable",
        notes: "Orthodontic not covered under DHMO plan.",
        typicalCost: 5000,
      },
      "Teeth Whitening": {
        covered: false,
        coveragePercentage: 0,
        frequencyLimit: "Not applicable",
        preAuthRequired: false,
        waitingPeriod: "Not applicable",
        notes: "Cosmetic procedures not covered.",
        typicalCost: 500,
      },
      "Tooth Extraction": {
        covered: true,
        coveragePercentage: 70,
        frequencyLimit: "As needed",
        preAuthRequired: true,
        waitingPeriod: "None",
        notes: "Surgical extractions require pre-auth.",
        typicalCost: 300,
      },
    },
  },

  "MetLife Dental": {
    payerName: "MetLife Dental",
    planType: "PPO",
    planName: "MetLife TakeAlong Dental PPO",
    payerPhone: "1-800-942-0854",
    annualMaximum: 2000,
    annualMaximumUsed: 450,
    deductible: 50,
    deductibleMet: true,
    deductibleRemaining: 0,
    preventiveCoverage: 100,
    basicCoverage: 80,
    majorCoverage: 50,
    orthodonticCoverage: 50,
    waitingPeriodBasic: "None",
    waitingPeriodMajor: "6 months",
    inNetworkCoverage: 80,
    outOfNetworkCoverage: 60,
    enrollmentDate: "2021-06-01",
    treatmentRules: {
      "Composite Filling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per surface per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Covered as basic restorative.", typicalCost: 250 },
      "Dental Crown": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per tooth per 5 years", preAuthRequired: false, waitingPeriod: "6 months", notes: "Major restorative.", typicalCost: 1300 },
      "Root Canal": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per tooth per lifetime", preAuthRequired: false, waitingPeriod: "None", notes: "Endodontic covered.", typicalCost: 900 },
      "Dental Implant": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per site per 7 years", preAuthRequired: true, waitingPeriod: "12 months", notes: "Pre-auth required.", typicalCost: 3500 },
      "Periodontal Scaling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per quadrant per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Periodontic covered.", typicalCost: 400 },
      "Orthodontics": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per lifetime", preAuthRequired: true, waitingPeriod: "12 months", notes: "Lifetime max $1,500.", typicalCost: 5000 },
      "Teeth Whitening": { covered: false, coveragePercentage: 0, frequencyLimit: "N/A", preAuthRequired: false, waitingPeriod: "N/A", notes: "Cosmetic not covered.", typicalCost: 500 },
      "Tooth Extraction": { covered: true, coveragePercentage: 80, frequencyLimit: "As needed", preAuthRequired: false, waitingPeriod: "None", notes: "Oral surgery covered.", typicalCost: 300 },
    },
  },

  "Guardian Dental": {
    payerName: "Guardian Dental",
    planType: "PPO",
    planName: "Guardian DentalGuard Preferred PPO",
    payerPhone: "1-800-541-7846",
    annualMaximum: 1750,
    annualMaximumUsed: 200,
    deductible: 50,
    deductibleMet: false,
    deductibleRemaining: 25,
    preventiveCoverage: 100,
    basicCoverage: 80,
    majorCoverage: 50,
    orthodonticCoverage: 50,
    waitingPeriodBasic: "None",
    waitingPeriodMajor: "None",
    inNetworkCoverage: 80,
    outOfNetworkCoverage: 55,
    enrollmentDate: "2023-09-01",
    treatmentRules: {
      "Composite Filling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per surface per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Basic restorative.", typicalCost: 250 },
      "Dental Crown": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per tooth per 5 years", preAuthRequired: false, waitingPeriod: "None", notes: "Major restorative.", typicalCost: 1300 },
      "Root Canal": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per tooth", preAuthRequired: false, waitingPeriod: "None", notes: "Endodontic covered.", typicalCost: 900 },
      "Dental Implant": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per site", preAuthRequired: true, waitingPeriod: "12 months", notes: "Pre-auth required for implants.", typicalCost: 3500 },
      "Periodontal Scaling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per quadrant per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Periodontic covered.", typicalCost: 400 },
      "Orthodontics": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per lifetime", preAuthRequired: true, waitingPeriod: "None", notes: "Pre-auth required.", typicalCost: 5000 },
      "Teeth Whitening": { covered: false, coveragePercentage: 0, frequencyLimit: "N/A", preAuthRequired: false, waitingPeriod: "N/A", notes: "Cosmetic not covered.", typicalCost: 500 },
      "Tooth Extraction": { covered: true, coveragePercentage: 80, frequencyLimit: "As needed", preAuthRequired: false, waitingPeriod: "None", notes: "Extractions covered.", typicalCost: 300 },
    },
  },

  "Humana Dental": {
    payerName: "Humana Dental",
    planType: "PPO",
    planName: "Humana Dental Value PPO",
    payerPhone: "1-800-800-4926",
    annualMaximum: 1500,
    annualMaximumUsed: 600,
    deductible: 75,
    deductibleMet: true,
    deductibleRemaining: 0,
    preventiveCoverage: 100,
    basicCoverage: 70,
    majorCoverage: 50,
    orthodonticCoverage: 0,
    waitingPeriodBasic: "6 months",
    waitingPeriodMajor: "12 months",
    inNetworkCoverage: 70,
    outOfNetworkCoverage: 50,
    enrollmentDate: "2022-08-01",
    treatmentRules: {
      "Composite Filling": { covered: true, coveragePercentage: 70, frequencyLimit: "Once per surface per 2 years", preAuthRequired: false, waitingPeriod: "6 months", notes: "Basic restorative with waiting period.", typicalCost: 250 },
      "Dental Crown": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per tooth per 5 years", preAuthRequired: true, waitingPeriod: "12 months", notes: "Major restorative, pre-auth required.", typicalCost: 1300 },
      "Root Canal": { covered: true, coveragePercentage: 70, frequencyLimit: "Once per tooth", preAuthRequired: false, waitingPeriod: "6 months", notes: "Endodontic with waiting period.", typicalCost: 900 },
      "Dental Implant": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per site", preAuthRequired: true, waitingPeriod: "24 months", notes: "Long waiting period for implants.", typicalCost: 3500 },
      "Periodontal Scaling": { covered: true, coveragePercentage: 70, frequencyLimit: "Once per quadrant per 2 years", preAuthRequired: false, waitingPeriod: "6 months", notes: "Periodontic with waiting period.", typicalCost: 400 },
      "Orthodontics": { covered: false, coveragePercentage: 0, frequencyLimit: "N/A", preAuthRequired: false, waitingPeriod: "N/A", notes: "Not covered.", typicalCost: 5000 },
      "Teeth Whitening": { covered: false, coveragePercentage: 0, frequencyLimit: "N/A", preAuthRequired: false, waitingPeriod: "N/A", notes: "Cosmetic not covered.", typicalCost: 500 },
      "Tooth Extraction": { covered: true, coveragePercentage: 70, frequencyLimit: "As needed", preAuthRequired: false, waitingPeriod: "None", notes: "Extractions covered.", typicalCost: 300 },
    },
  },

  "United Concordia": {
    payerName: "United Concordia",
    planType: "PPO",
    planName: "United Concordia Dental Preferred PPO",
    payerPhone: "1-800-332-0366",
    annualMaximum: 2000,
    annualMaximumUsed: 150,
    deductible: 50,
    deductibleMet: true,
    deductibleRemaining: 0,
    preventiveCoverage: 100,
    basicCoverage: 80,
    majorCoverage: 60,
    orthodonticCoverage: 50,
    waitingPeriodBasic: "None",
    waitingPeriodMajor: "None",
    inNetworkCoverage: 80,
    outOfNetworkCoverage: 60,
    enrollmentDate: "2020-03-01",
    treatmentRules: {
      "Composite Filling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per surface per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Basic restorative, no waiting period.", typicalCost: 250 },
      "Dental Crown": { covered: true, coveragePercentage: 60, frequencyLimit: "Once per tooth per 5 years", preAuthRequired: false, waitingPeriod: "None", notes: "Better major coverage at 60%.", typicalCost: 1300 },
      "Root Canal": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per tooth", preAuthRequired: false, waitingPeriod: "None", notes: "Endodontic covered.", typicalCost: 900 },
      "Dental Implant": { covered: true, coveragePercentage: 60, frequencyLimit: "Once per site", preAuthRequired: true, waitingPeriod: "None", notes: "Pre-auth required, no waiting period.", typicalCost: 3500 },
      "Periodontal Scaling": { covered: true, coveragePercentage: 80, frequencyLimit: "Once per quadrant per 2 years", preAuthRequired: false, waitingPeriod: "None", notes: "Periodontic covered.", typicalCost: 400 },
      "Orthodontics": { covered: true, coveragePercentage: 50, frequencyLimit: "Once per lifetime", preAuthRequired: true, waitingPeriod: "None", notes: "Lifetime max $2,000.", typicalCost: 5000 },
      "Teeth Whitening": { covered: false, coveragePercentage: 0, frequencyLimit: "N/A", preAuthRequired: false, waitingPeriod: "N/A", notes: "Cosmetic not covered.", typicalCost: 500 },
      "Tooth Extraction": { covered: true, coveragePercentage: 80, frequencyLimit: "As needed", preAuthRequired: false, waitingPeriod: "None", notes: "Oral surgery covered.", typicalCost: 300 },
    },
  },
};

export function getPayerData(payerName: string): PayerBenefitData | null {
  return MOCK_PAYER_DATABASE[payerName] || null;
}

export { MOCK_PAYER_DATABASE };
